version: '3'

services:
  jupyterlab:
    image: jupyter/tensorflow-notebook:latest
    user: root
    environment:
      NB_UID: 1000
      NB_GID: 100
      GRANT_SUDO: "yes"
    volumes:
       - "./work:/home/jovyan/work"
    privileged: true
    ports:
      - "8888:8888"
    restart: unless-stopped
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
